apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-tvplatform-factory-cacheserver
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./staging/tvplatform-factory-cacheserver
    repoURL: git@github.com:OORO-Platform/tvplatform-devops-gitops.git
    targetRevision: feat/staging
  syncPolicy:
    automated:
      # prune: true # Automatically deletes resources that are no longer defined in the Git repo
      selfHeal: true # Automatically syncs when a resource is out of sync
    syncOptions:
    - CreateNamespace=true # Ensures namespace is created if it doesn't exist
    - ApplyOutOfSyncOnly=true # Apply only out-of-sync changes
    - Replace=true # Forces resources to be replaced
