apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-tvplatform-admin-authentication
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./staging/tvplatform-admin-authentication
    repoURL: git@github.com:OORO-Platform/tvplatform-devops-gitops.git
    targetRevision: feat/staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # Ensures namespace is created if it doesn't exist
    - ApplyOutOfSyncOnly=true # Apply only out-of-sync changes
    - Replace=true # Forces resources to be replaced
