apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-tvplatform-user-consent
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./staging/tvplatform-user-consent
    repoURL: https://github.com/arwaabdo/argod-gitops.git
  syncPolicy:
    automated: {}
---
