
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: default/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    # nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    # nginx.ingress.kubernetes.io/auth-tls-secret: "default/client-auth-ca-secret"
    # nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # nginx.ingress.kubernetes.io/auth-tls-verify-depth: "2"
    
    
  name: tvplatform-dev-device
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.dev.ooro.co.uk
        - dev.ooro.co.uk
      secretName: letsencrypt-dev
      # secretName: tls-secrett
  rules:
    - host: www.dev.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-dev-device
                port:
                  number: 8000
    - host: dev.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-dev-device
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: default/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/rewrite-target: /ELARABY/$1/METADATA/v1/Published/$1.json
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* ^/update/([A-Z0-9]+)\.json$) {
          set $device_id $1;
          return 302 /ELARABY/$device_id/METADATA/v1/Published/$device_id.json;
      }
  name: tvplatform-dev-device-other
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.dev.ooro.co.uk
        - dev.ooro.co.uk
      secretName: letsencrypt-dev
  rules:
    - host: www.dev.ooro.co.uk
      http:
        paths:
          - path: "/update/([A-Z0-9]+).json"
            pathType: ImplementationSpecific
            backend:
              service:
                name: tvplatform-dev-device
                port:
                  number: 8000
    - host: dev.ooro.co.uk
      http:
        paths:
          - path: "/update/([A-Z0-9]+).json"
            pathType: ImplementationSpecific
            backend:
              service:
                name: tvplatform-dev-device
                port:
                  number: 8000
