
apiVersion: v1
kind: Service
metadata:
  name: tvplatform-user-consent
  namespace: users
spec:
  type: NodePort
  selector:
    app: tvplatform-user-consent
  ports:
  - name: http
    port: 8000 # svc port
    targetPort: 8000 # app port
    # nodePort: 30003  # Port accessible externally on each node
