apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-userservice

spec:
  acme:
    email: chris.aldworth@oceanbluesoftware.co.uk
    privateKeySecretRef:
      name: letsencrypt-userservice
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-userservice
  namespace: users
spec:
  dnsNames:
    - www.uapi.ooro.co.uk
    - uapi.ooro.co.uk
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-userservice
  secretName: letsencrypt-userservice
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-userservice
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: tvplatform-user-bk
  namespace: users
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.uapi.ooro.co.uk
        - uapi.ooro.co.uk
      secretName: letsencrypt-userservice
  rules:
    - host: www.uapi.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-gateway
                port:
                  number: 8000
    - host: uapi.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-gateway
                port:
                  number: 8000