apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-dev-device-dev
  namespace: default
  labels:
    app: tvplatform-dev-device-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-dev-device-dev
  template:
    metadata:
      labels:
        app: tvplatform-dev-device-dev
    spec:
      containers:
      - name: tvplatform-dev-device-dev
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-dev-device:8 # will be updated by jenkins PRs
        imagePullPolicy: Always
      imagePullSecrets:
      - name: obs-tvplatform-backend
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - dev
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "dev"
        effect: "NoExecute"