apiVersion: batch/v1
kind: Job
metadata:
  name: tvplatform-dev-device-dbmigration
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync  # Run this Job before any other resource
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: migration
        image: python:3.11-slim  # Replace with your desired Python version
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git &&
            git clone https://${GITHUB_TOKEN}@github.com/OceanBlueSoftware/tvplatform-dev-device.git /app &&
            cd /app &&
            pip3 install pip --upgrade &&
            pip3 install poetry &&
            poetry install &&
            poetry run alembic upgrade head
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token-secret
              key: GITHUB_TOKEN
        envFrom:
        - secretRef:
            name: tvplatform-dev-device-dev  # Mount environment variables from the secret
      restartPolicy: Never  # Specify the restart policy
