apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tvplatform-admin-frontend
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./tvplatform-admin-frontend
    repoURL: https://github.com/arwaabdo/argod-gitops.git
  syncPolicy:
    automated: {}
