apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-user-userservice
  namespace: users
  labels:
    app: tvplatform-user-userservice
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-user-userservice
      env: staging
  template:
    metadata:
      labels:
        app: tvplatform-user-userservice
        env: staging
    spec:
      containers:
      - name: tvplatform-user-userservice
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-user-userservice:3-staging # will be updated by jenkins PRs
        imagePullPolicy: Always
      imagePullSecrets:
      - name: obs-tvplatform-backend