apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-user-consent
  namespace: default
  labels:
    app: tvplatform-user-consent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-user-consent
  template:
    metadata:
      labels:
        app: tvplatform-user-consent
    spec:
      containers:
      - name: tvplatform-user-consent
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-user-consent:6-staging # will be updated by jenkins PRs
        imagePullPolicy: Always
      imagePullSecrets:
      - name: obs-tvplatform-backend