apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-generalservices-notifications
  namespace: users
  labels:
    app: tvplatform-generalservices-notifications
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-generalservices-notifications
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-generalservices-notifications
        env: dev
    spec:
      containers:
      - name: tvplatform-generalservices-notifications
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-generalservices-notifications:2-dev # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-generalservices-notifications-dev
      imagePullSecrets:
      - name: obs-tvplatform-backend