apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-tvplatform-user-gateway

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./production/tvplatform-user-gateway
    repoURL: https://github.com/arwaabdo/argod-gitops.git
  syncPolicy:
    automated: {}
