apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-tvplatform-user-gateway
  namespace: argocd
spec:
  destination:
    namespace: users
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./prod/tvplatform-user-gateway
    repoURL: https://github.com/arwaabdo/argod-gitops.git
    targetRevision: feat/prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - Replace=true
  ignoreDifferences:
  - group: networking.k8s.io
    kind: Ingress
    name: tvplatform-user-gateway
    # jqPathExpressions:
    # - .spec
  - group: cert-manager.io
    kind: Certificate
    name: tvplatform-user-gateway*
    jqPathExpressions:
    - .spec
