apiVersion: v1
kind: Service
metadata:
  name: tvplatform-admin-product
  namespace: default
spec:
  type: NodePort
  selector:
    app: tvplatform-admin-product
  ports:
  - name: http
    port: 8000 # svc port
    targetPort: 8000 # app port
    nodePort: 30005 # Port accessible externally on each node
