apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-user-identity
  namespace: default
  labels:
    app: tvplatform-user-identity
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-user-identity
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-user-identity
        env: dev
    spec:
      containers:
      - name: tvplatform-user-identity
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-user-identity:13-dev # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        # - secretRef:
        #     name: tvplatform-admin-authentication-dev
      imagePullSecrets:
      - name: obs-tvplatform-backend