apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-authentication
  namespace: default
  labels:
    app: tvplatform-admin-authentication
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-authentication
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-admin-authentication
        env: dev
    spec:
      containers:
      - name: tvplatform-admin-authentication
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-authentication:95-dev # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-admin-authentication-dev
      imagePullSecrets:
      - name: obs-tvplatform-backend
