apiVersion: v1
kind: Service
metadata:
  name: tvplatform-admin-authentication
  namespace: default
spec:
  type: NodePort
  selector:
    app: tvplatform-admin-authentication
    env: dev
  ports:
  - name: http
    port: 8000 # svc port
    targetPort: 8000 # app port
    # nodePort: 30000   # Port accessible externally on each node
