apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-security
  namespace: default
  labels:
    app: tvplatform-admin-security
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-security
      env: prod
  template:
    metadata:
      labels:
        app: tvplatform-admin-security
        env: prod
    spec:
      containers:
      - name: tvplatform-admin-security
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-security:3-prod # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-admin-security-prod
      serviceAccountName: update-secret-and-ingress
      serviceAccount: update-secret-and-ingress
      imagePullSecrets:
      - name: obs-tvplatform-backend
