apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-userfront
spec:
  acme:
    email: chris.aldworth@oceanbluesoftware.co.uk
    privateKeySecretRef:
      name: letsencrypt-userfront
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-userfront
  namespace: users
spec:
  dnsNames:
    - www.user.ooro.co.uk
    - user.ooro.co.uk
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-userfront
  secretName: letsencrypt-userfront
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-userfront
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: tvplatform-user-front
  namespace: users
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.user.ooro.co.uk
        - user.ooro.co.uk
      secretName: letsencrypt-userfront
  rules:
    - host: www.user.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-frontend
                port:
                  number: 80
    - host: user.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-frontend
                port:
                  number: 80