apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-user-userservice
  namespace: users
  labels:
    app: tvplatform-user-userservice
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-user-userservice
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-user-userservice
        env: dev
    spec:
      containers:
      - name: tvplatform-user-userservice
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-user-userservice:2-dev # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-user-userservice-dev
      imagePullSecrets:
      - name: obs-tvplatform-backend