apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-security
  namespace: default
  labels:
    app: tvplatform-admin-security
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-security
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-admin-security
        env: dev
    spec:
      serviceAccountName: update-secret-and-ingress
      containers:
      - name: tvplatform-admin-security
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-security:69-dev # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-admin-security-dev
      imagePullSecrets:
      - name: obs-tvplatform-backend
 
