apiVersion: v1
kind: Service
metadata:
  name: tvplatform-admin-authentication
  namespace: default
spec:
  type: NodePort
  selector:
    app: tvplatform-admin-authentication
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000   # Port accessible externally on each node
