---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: usergw-certificate
  namespace: users
spec:
  dnsNames:
    - www.uapi.staging-ooro.co.uk
    - uapi.staging-ooro.co.uk
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: usergw-certificate
  secretName: usergw-certificate
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: usergw-certificate
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: tvplatform-user-gateway
  namespace: users
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.uapi.staging-ooro.co.uk
        - uapi.staging-ooro.co.uk
      secretName: usergw-certificate
  rules:
    - host: www.uapi.staging-ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-gateway
                port:
                  number: 8000
    - host: uapi.staging-ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-gateway
                port:
                  number: 8000
