apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-frontend
  namespace: default
  labels:
    app: tvplatform-admin-frontend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-frontend
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-admin-frontend
        env: dev
    spec:
      containers:
      - name: tvplatform-admin-frontend
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-frontend:15-dev # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-admin-frontend-dev
      imagePullSecrets:
      - name: obs-tvplatform-backend
