
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-userfront
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: tvplatform-user-front
  namespace: users
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.user.ooro.co.uk
        - user.ooro.co.uk
      secretName: letsencrypt-userfront
  rules:
    - host: www.user.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-frontend
                port:
                  number: 80
    - host: user.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-frontend
                port:
                  number: 80