apiVersion: v1
kind: Service
metadata:
  name: tvplatform-user-frontend
  namespace: users
spec:
  type: NodePort
  selector:
    app: tvplatform-user-frontend
    env: staging
  ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 3000
        nodePort: 30617
