apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-gateway
  namespace: default
  labels:
    app: tvplatform-admin-gateway
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-gateway
      env: staging
  template:
    metadata:
      labels:
        app: tvplatform-admin-gateway
        env: staging
    spec:
      containers:
      - name: tvplatform-admin-gateway
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-gateway:2-staging # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-admin-gateway-staging
      imagePullSecrets:
      - name: obs-tvplatform-backend
