---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admingateway-cert
spec:
  dnsNames:
    - www.api.staging-ooro.co.uk
    - api.staging-ooro.co.uk
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: admingateway-cert
  secretName: admingateway-cert
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: admingateway-cert
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: tvplatform-admin-bk
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.api.staging-ooro.co.uk
        - api.staging-ooro.co.uk
      secretName: admingateway-cert
  rules:
    - host: www.api.staging-ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-admin-gateway
                port:
                  number: 8000
    - host: api.staging-ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-admin-gateway
                port:
                  number: 8000