
apiVersion: v1
kind: Service
metadata:
  name: tvplatform-admin-gateway-staging
  namespace: default
spec:
  type: NodePort
  selector:
    app: tvplatform-admin-gateway-staging
    env: staging
  ports:
  - name: http
    port: 8000 # svc port
    targetPort: 8000 # app port
    # nodePort: 30001  # Port accessible externally on each node
