apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: uploadms-certificate
  namespace: default
spec:
  dnsNames:
    - www.uploadms.dev-ooro.co.uk
    - uploadms.dev-ooro.co.uk
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: uploadms-certificate
  secretName: uploadms-certificate
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uploadms
  namespace: default
  annotations:
    cert-manager.io/issuer: uploadms-certificate
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true' 
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.uploadms.dev-ooro.co.uk
        - uploadms.dev-ooro.co.uk
      secretName: uploadms-certificate
  rules:
    - host: www.uploadms.dev-ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-admin-uploadms
                port:
                  number: 8000
    - host: uploadms.dev-ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-admin-uploadms
                port:
                  number: 8000
