apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: oro-ca
spec:
  acme:
    email: chris.aldworth@oceanbluesoftware.co.uk
    privateKeySecretRef:
      name: oro-ca
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    argocd.argoproj.io/instance: tvplatform-user-frontend-home
  name: oro-ca
spec:
  dnsNames:
    - www.ooro.co.uk
    - ooro.co.uk
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: oro-ca
  secretName: oro-ca
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: oro-ca
  name: tvplatform-user-frontend-home
  namespace: default
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.ooro.co.uk
        - ooro.co.uk
      secretName: oro-ca
  rules:
    - host: www.ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-frontend-home
                port:
                  number: 80
    - host: ooro.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tvplatform-user-frontend-home
                port:
                  number: 80