apiVersion: v1
kind: Service
metadata:
  name: tvplatform-user-identity
  namespace: default
spec:
  type: NodePort
  selector:
    app: tvplatform-user-identity
  ports:
  - name: http
    port: 8000 # svc port
    targetPort: 8000 # app port
    # nodePort: 30004 # Port accessible externally on each node
