apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-gateway
  namespace: default
  labels:
    app: tvplatform-admin-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-gateway
  template:
    metadata:
      labels:
        app: tvplatform-admin-gateway
    spec:
      containers:
      - name: tvplatform-admin-gateway
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-gateway:24 # will be updated by jenkins PRs
        imagePullPolicy: Always
      imagePullSecrets:
      - name: obs-tvplatform-backend
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - production
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "production"
        effect: "PreferNoSchedule"
