apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-admin-product
  namespace: default
  labels:
    app: tvplatform-admin-product
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-admin-product
      env: dev
  template:
    metadata:
      labels:
        app: tvplatform-admin-product
        env: dev
    spec:
      containers:
      - name: tvplatform-admin-product
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-admin-product:44-staging # will be updated by jenkins PRs
        imagePullPolicy: Always
      imagePullSecrets:
      - name: obs-tvplatform-backend
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - dev
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"