apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvplatform-user-identity
  namespace: default
  labels:
    app: tvplatform-user-identity
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvplatform-user-identity
      env: staging
  template:
    metadata:
      labels:
        app: tvplatform-user-identity
        env: staging
    spec:
      containers:
      - name: tvplatform-user-identity
        image: registry.digitalocean.com/obs-tvplatform-backend/tvplatform-user-identity:7-staging # will be updated by jenkins PRs
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: tvplatform-admin-authentication-staging
      imagePullSecrets:
      - name: obs-tvplatform-backend
